#!/bin/sh

alias .gpo="pushd $POET"
alias .gpoem="pushd $POET_POEM"
alias .guser="pushd $POET_USER"
alias zz="zjot new"
alias bg="zjot new [bg] "
alias food="zjot new [food]"
alias ins="zjot new [humalog]"
alias lins="zjot new [tresiba]"

alias user=".bozo user"
echo [BOZO]: $*
echo [BOZO]: enter [user] for a better user experience.
