#!/bin/bash

here=$(dirname ${__BLESSED_CLIENT__})

bozo_dot() {
    ${__BLESSED_DOT__} $here/dot$*
}

if [ -f $here/dot$1 ]; then
    bozo_dot $*
else
    ${__BLESSED_DOT__} ${__BLESSED_CLIENT__}.$*
fi
