#!/source/this/sh
cd ..

export_ () { export $1=$2; }
export_ BOZO        ${PWD}
export_ BOZO_BIN    ${BOZO}/bin
export_ BOZO_BUILD  ${BOZO}/.build
export_ BOZO_VENDOR ${BOZO_BUILD}/.vendor

.bozo () {
    local p=${BOZO_BIN}/src.bozo
    [ "$1" == "" ] && { . ${p}.__null__ $* ; return $?; }
    [ -f ${p}.$1 ] && { . ${p}.$*          ; return $?; }
    [ -f ${p}.$1 ] || { . ${p}.__bad__ $*  ; return $?; }
}

bozo () {
    local p=${BOZO_BIN}/bozo
    [ "$1" == "" ] && { ${p}.__null__ $* ; return $?; }
    [ -f ${p}.$1 ] && { ${p}.$*          ; return $?; }
    [ -f ${p}.$1 ] || { ${p}.__bad__ $*  ; return $?; }
}

. ./__init__ $*

