#!/source/this/sh
cd ..
poet.baptize ${PWD}/bin/bl.bozo ${HOME}/.local/bin/bl.user

export_ () { export $1=$2; }
export_ BOZO        ${PWD}
export_ BOZO_BIN    ${BOZO}/bin
export_ BOZO_BUILD  ${BOZO}/.build
export_ BOZO_VENDOR ${BOZO_BUILD}/.vendor
export_ BLESSED_BOZO_BIN ${BOZO_BIN}
